baseURL = "https://anikethjain.com"
languageCode = "en-us"
title = "Anikethjain's personal homepage"
paginate = 20

[params]
subtitle = "Write on Tech, business, and life"
thumbnail = "thumb.jpg"

[taxonomies]
   tag = "tags"
   author = "authors"

[menu]
   [[menu.header]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

   [[menu.header]]
      identifier = "blog"
      name = "Blog"
      url = "/blog"
      weight = 2
